"""Add sha256 to Content

Revision ID: 360debe251bb
Revises: e6b8c0d3f5a2
Create Date: 2026-08-07 09:50:55.403949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '360debe251bb'
down_revision: Union[str, None] = 'e6b8c0d3f5a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('sha256', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content', 'sha256')
    # ### end Alembic commands ###
