"""Add sha256 to AppRelease

Revision ID: 4006a4cddce5
Revises: ca4a90396f1a
Create Date: 2026-08-07 20:32:08.590221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4006a4cddce5'
down_revision: Union[str, None] = 'ca4a90396f1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_releases', sa.Column('sha256', sa.String(length=64), nullable=True))
    op.drop_column('app_releases', 'release_notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_releases', sa.Column('release_notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('app_releases', 'sha256')
    # ### end Alembic commands ###
