"""Add duration_ms to Content

Revision ID: 458040e74f59
Revises: 4006a4cddce5
Create Date: 2026-08-07 22:10:18.756337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '458040e74f59'
down_revision: Union[str, None] = '4006a4cddce5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('duration_ms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content', 'duration_ms')
    # ### end Alembic commands ###
