"""Add TV capability columns

Revision ID: 496ec6d8c368
Revises: 458040e74f59
Create Date: 2026-08-08 14:59:41.437875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '496ec6d8c368'
down_revision: Union[str, None] = '458040e74f59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screens', sa.Column('screen_width', sa.Integer(), nullable=True))
    op.add_column('screens', sa.Column('screen_height', sa.Integer(), nullable=True))
    op.add_column('screens', sa.Column('refresh_rate', sa.Integer(), nullable=True))
    op.add_column('screens', sa.Column('total_ram_mb', sa.Integer(), nullable=True))
    op.add_column('screens', sa.Column('available_ram_mb', sa.Integer(), nullable=True))
    op.add_column('screens', sa.Column('total_storage_mb', sa.Integer(), nullable=True))
    op.add_column('screens', sa.Column('free_storage_mb', sa.Integer(), nullable=True))
    op.add_column('screens', sa.Column('supported_video_codecs', sa.JSON(), nullable=True))
    op.add_column('screens', sa.Column('max_decode_width', sa.Integer(), nullable=True))
    op.add_column('screens', sa.Column('max_decode_height', sa.Integer(), nullable=True))
    op.add_column('screens', sa.Column('manufacturer', sa.String(), nullable=True))
    op.add_column('screens', sa.Column('model', sa.String(), nullable=True))
    op.add_column('screens', sa.Column('android_version', sa.String(), nullable=True))
    op.add_column('screens', sa.Column('sdk_int', sa.Integer(), nullable=True))
    op.add_column('screens', sa.Column('network_type', sa.String(), nullable=True))
    op.add_column('screens', sa.Column('timezone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screens', 'timezone')
    op.drop_column('screens', 'network_type')
    op.drop_column('screens', 'sdk_int')
    op.drop_column('screens', 'android_version')
    op.drop_column('screens', 'model')
    op.drop_column('screens', 'manufacturer')
    op.drop_column('screens', 'max_decode_height')
    op.drop_column('screens', 'max_decode_width')
    op.drop_column('screens', 'supported_video_codecs')
    op.drop_column('screens', 'free_storage_mb')
    op.drop_column('screens', 'total_storage_mb')
    op.drop_column('screens', 'available_ram_mb')
    op.drop_column('screens', 'total_ram_mb')
    op.drop_column('screens', 'refresh_rate')
    op.drop_column('screens', 'screen_height')
    op.drop_column('screens', 'screen_width')
    # ### end Alembic commands ###
