"""P3 device enrollment and processing retries

Revision ID: 79d608748198
Revises: a8808f58ffa1
Create Date: 2026-08-07 12:35:47.519228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79d608748198'
down_revision: Union[str, None] = 'a8808f58ffa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollment_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrollment_tokens_id'), 'enrollment_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_enrollment_tokens_organization_id'), 'enrollment_tokens', ['organization_id'], unique=False)
    op.create_index(op.f('ix_enrollment_tokens_token'), 'enrollment_tokens', ['token'], unique=True)
    op.add_column('content', sa.Column('processing_retries', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('screens', sa.Column('device_secret_hash', sa.String(), nullable=True))
    op.add_column('screens', sa.Column('installation_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screens', 'installation_id')
    op.drop_column('screens', 'device_secret_hash')
    op.drop_column('content', 'processing_retries')
    op.drop_index(op.f('ix_enrollment_tokens_token'), table_name='enrollment_tokens')
    op.drop_index(op.f('ix_enrollment_tokens_organization_id'), table_name='enrollment_tokens')
    op.drop_index(op.f('ix_enrollment_tokens_id'), table_name='enrollment_tokens')
    op.drop_table('enrollment_tokens')
    # ### end Alembic commands ###
