"""Add MediaRendition and content status

Revision ID: a8808f58ffa1
Revises: 190f5bb76578
Create Date: 2026-08-07 11:46:43.020009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8808f58ffa1'
down_revision: Union[str, None] = '190f5bb76578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_renditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('resolution', sa.String(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('rotation', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('codec', sa.String(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_renditions_content_id'), 'media_renditions', ['content_id'], unique=False)
    op.create_index(op.f('ix_media_renditions_id'), 'media_renditions', ['id'], unique=False)
    op.add_column('content', sa.Column('status', sa.String(), nullable=False, server_default='ready'))
    op.add_column('content', sa.Column('failed_reason', sa.String(), nullable=True))
    # (Spurious datetime and unique constraint changes removed)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # (Spurious datetime and unique constraint changes removed)
    op.drop_column('content', 'failed_reason')
    op.drop_column('content', 'status')
    op.drop_index(op.f('ix_media_renditions_id'), table_name='media_renditions')
    op.drop_index(op.f('ix_media_renditions_content_id'), table_name='media_renditions')
    op.drop_table('media_renditions')
    # ### end Alembic commands ###
