"""P6 realtime and control

Revision ID: af8fee5f1e31
Revises: d85d02c520ee
Create Date: 2026-08-07 19:22:51.331889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af8fee5f1e31'
down_revision: Union[str, None] = 'd85d02c520ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergency_broadcasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_broadcasts_id'), 'emergency_broadcasts', ['id'], unique=False)
    op.create_index(op.f('ix_emergency_broadcasts_organization_id'), 'emergency_broadcasts', ['organization_id'], unique=False)
    op.add_column('screen_groups', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('screen_groups', sa.Column('is_dynamic', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('screen_groups', sa.Column('dynamic_criteria', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_screen_groups_parent_id'), 'screen_groups', ['parent_id'], unique=False)
    op.create_foreign_key(None, 'screen_groups', 'screen_groups', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'screen_groups', type_='foreignkey')
    op.drop_index(op.f('ix_screen_groups_parent_id'), table_name='screen_groups')
    op.drop_column('screen_groups', 'dynamic_criteria')
    op.drop_column('screen_groups', 'is_dynamic')
    op.drop_column('screen_groups', 'parent_id')
    op.drop_index(op.f('ix_emergency_broadcasts_organization_id'), table_name='emergency_broadcasts')
    op.drop_index(op.f('ix_emergency_broadcasts_id'), table_name='emergency_broadcasts')
    op.drop_table('emergency_broadcasts')
    # ### end Alembic commands ###
