"""P7 fleet operations

Revision ID: ca4a90396f1a
Revises: af8fee5f1e31
Create Date: 2026-08-07 19:45:57.857023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca4a90396f1a'
down_revision: Union[str, None] = 'af8fee5f1e31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_code', sa.Integer(), nullable=False),
    sa.Column('version_name', sa.String(), nullable=False),
    sa.Column('apk_url', sa.String(), nullable=False),
    sa.Column('release_notes', sa.String(), nullable=True),
    sa.Column('mandatory', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_releases_id'), 'app_releases', ['id'], unique=False)
    op.create_index(op.f('ix_app_releases_version_code'), 'app_releases', ['version_code'], unique=True)
    op.create_table('screenshot_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('screen_id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['screen_id'], ['screens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screenshot_logs_id'), 'screenshot_logs', ['id'], unique=False)
    op.create_index(op.f('ix_screenshot_logs_organization_id'), 'screenshot_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_screenshot_logs_screen_id'), 'screenshot_logs', ['screen_id'], unique=False)
    op.add_column('screen_groups', sa.Column('target_version_code', sa.Integer(), nullable=True))
    op.drop_index('ix_screen_groups_name', table_name='screen_groups')
    op.drop_constraint('screen_groups_parent_id_fkey', 'screen_groups', type_='foreignkey')
    op.create_foreign_key(None, 'screen_groups', 'app_releases', ['target_version_code'], ['version_code'], ondelete='SET NULL')
    op.create_foreign_key(None, 'screen_groups', 'screen_groups', ['parent_id'], ['id'], ondelete='SET NULL')
    op.add_column('screens', sa.Column('target_version_code', sa.Integer(), nullable=True))
    op.add_column('screens', sa.Column('update_status', sa.String(), nullable=True))
    op.alter_column('screens', 'last_seen',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('screens', 'last_error',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_foreign_key(None, 'screens', 'app_releases', ['target_version_code'], ['version_code'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'screens', type_='foreignkey')
    op.alter_column('screens', 'last_error',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('screens', 'last_seen',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('screens', 'update_status')
    op.drop_column('screens', 'target_version_code')
    op.drop_constraint(None, 'screen_groups', type_='foreignkey')
    op.drop_constraint(None, 'screen_groups', type_='foreignkey')
    op.create_foreign_key('screen_groups_parent_id_fkey', 'screen_groups', 'screen_groups', ['parent_id'], ['id'])
    op.create_index('ix_screen_groups_name', 'screen_groups', ['name'], unique=True)
    op.drop_column('screen_groups', 'target_version_code')
    op.drop_index(op.f('ix_screenshot_logs_screen_id'), table_name='screenshot_logs')
    op.drop_index(op.f('ix_screenshot_logs_organization_id'), table_name='screenshot_logs')
    op.drop_index(op.f('ix_screenshot_logs_id'), table_name='screenshot_logs')
    op.drop_table('screenshot_logs')
    op.drop_index(op.f('ix_app_releases_version_code'), table_name='app_releases')
    op.drop_index(op.f('ix_app_releases_id'), table_name='app_releases')
    op.drop_table('app_releases')
    # ### end Alembic commands ###
