"""Add Campaign and PlayLogHourlyRollup

Revision ID: d85d02c520ee
Revises: 1546beb2a7d6
Create Date: 2026-08-07 18:32:01.014959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd85d02c520ee'
down_revision: Union[str, None] = '1546beb2a7d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.create_index(op.f('ix_campaigns_organization_id'), 'campaigns', ['organization_id'], unique=False)
    op.create_table('play_log_hourly_rollups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('screen_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.Column('date_hour', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_plays', sa.Integer(), nullable=False),
    sa.Column('completed_plays', sa.Integer(), nullable=False),
    sa.Column('partial_plays', sa.Integer(), nullable=False),
    sa.Column('error_plays', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['media_id'], ['content.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['screen_id'], ['screens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_play_log_hourly_rollups_campaign_id'), 'play_log_hourly_rollups', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_play_log_hourly_rollups_date_hour'), 'play_log_hourly_rollups', ['date_hour'], unique=False)
    op.create_index(op.f('ix_play_log_hourly_rollups_id'), 'play_log_hourly_rollups', ['id'], unique=False)
    op.create_index(op.f('ix_play_log_hourly_rollups_media_id'), 'play_log_hourly_rollups', ['media_id'], unique=False)
    op.create_index(op.f('ix_play_log_hourly_rollups_organization_id'), 'play_log_hourly_rollups', ['organization_id'], unique=False)
    op.create_index(op.f('ix_play_log_hourly_rollups_screen_id'), 'play_log_hourly_rollups', ['screen_id'], unique=False)
    op.create_index('ix_play_log_hourly_rollups_unique', 'play_log_hourly_rollups', ['organization_id', 'campaign_id', 'screen_id', 'media_id', 'date_hour'], unique=True)
    op.add_column('play_logs', sa.Column('aggregated', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_play_logs_aggregated'), 'play_logs', ['aggregated'], unique=False)
    op.create_foreign_key(None, 'play_logs', 'campaigns', ['campaign_id'], ['id'])
    op.add_column('playlists', sa.Column('campaign_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_playlists_campaign_id'), 'playlists', ['campaign_id'], unique=False)
    op.create_foreign_key(None, 'playlists', 'campaigns', ['campaign_id'], ['id'], ondelete='SET NULL')

    # ### Custom Backfill Logic ###
    op.execute(
        """
        INSERT INTO campaigns (organization_id, name, created_at, updated_at)
        SELECT DISTINCT organization_id, name, NOW(), NOW()
        FROM playlists;
        """
    )
    op.execute(
        """
        UPDATE playlists
        SET campaign_id = c.id
        FROM campaigns c
        WHERE playlists.name = c.name AND playlists.organization_id = c.organization_id;
        """
    )
    op.execute(
        """
        UPDATE play_logs
        SET campaign_id = p.campaign_id
        FROM playlists p
        WHERE play_logs.playlist_id = p.id;
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'playlists', type_='foreignkey')
    op.drop_index(op.f('ix_playlists_campaign_id'), table_name='playlists')
    op.drop_column('playlists', 'campaign_id')
    op.drop_constraint(None, 'play_logs', type_='foreignkey')
    op.drop_index(op.f('ix_play_logs_aggregated'), table_name='play_logs')
    op.drop_column('play_logs', 'aggregated')
    op.drop_index('ix_play_log_hourly_rollups_unique', table_name='play_log_hourly_rollups')
    op.drop_index(op.f('ix_play_log_hourly_rollups_screen_id'), table_name='play_log_hourly_rollups')
    op.drop_index(op.f('ix_play_log_hourly_rollups_organization_id'), table_name='play_log_hourly_rollups')
    op.drop_index(op.f('ix_play_log_hourly_rollups_media_id'), table_name='play_log_hourly_rollups')
    op.drop_index(op.f('ix_play_log_hourly_rollups_id'), table_name='play_log_hourly_rollups')
    op.drop_index(op.f('ix_play_log_hourly_rollups_date_hour'), table_name='play_log_hourly_rollups')
    op.drop_index(op.f('ix_play_log_hourly_rollups_campaign_id'), table_name='play_log_hourly_rollups')
    op.drop_table('play_log_hourly_rollups')
    op.drop_index(op.f('ix_campaigns_organization_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
